service:
  host: 0.0.0.0
  port: 8000

structure:
  file_path: test/test.gjf
  charge: 0
  spin: 1

task:
  optimization:
    run: True
    traj: True
    optimized_structure: True
    fmax: 0.01
    steps: 100000000
  spe_calculation:
    run: True
  vib_calculation:
    run: False
